name: Create Tag & Release

on:
  push:
    branches:
      - main
      
jobs:
  tag_release:
    name: Create Tag and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Git Semantic Version
      id: semver
      uses: PaulHatch/semantic-version@v5.0.0-alpha2
      with:
        branch: main
            
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.semver.outputs.version_tag}}
        release_name: ${{steps.semver.outputs.version_tag}}
        draft: false
        prerelease: false
      
    
